---
# tasks file for docker
- name: Install packages
  apt:
    name: 
      - docker.io
      - docker-compose
    state: latest
- name: Setup compose directory
  ansible.builtin.file:
    path: /etc/docker/compose
    state: directory
    mode: '0700'
- name: Install compose systemd conf
  ansible.builtin.copy:
    src: files/docker-compose.conf
    dest: /etc/systemd/system/docker-compose@.service
    owner: root
    group: root
    mode: '0644'